services:
  shinyapp:
    image: victor2wy/rbiotechsalary # dockerhub
    ports:
      - "3838:3838"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    user: postgres # non-root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    user: "1000:1000"

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT} # internal port
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # nginx:
  #   image: nginx-latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   restart: unless-stopped

volumes:
  postgres_data: 